#MY-SQL 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boardsj?serverTimeZone=UTC&CharacterEncoding=UTF-8
    username: root
    password: mysql

  security:
    user:
      name: user
      password: 1234
    oauth2:
      client:
        registration:
          google:
            client-id: 57149116539-gced3kiomrhpnq61c8jhsp96eakjtoh2.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          kakao:
            client-id: de117df7c77c27ef6224c1e24999e14f
            client-secret: c51e2N0qiR6FVRzYEhzBdzu8wl0MPG5r
            client-authentication-method: POST
            #이걸 안넣어주니 오류남
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id


#MyBatis 설정
mybatis:
  type-aliases-package: com.adnstyle.boardSJ.dto
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true

#Server 설정
server:
  port: 8081
  servlet:
    session:
      timeout: 1800

